export default {
    welcomeMessage: 'Hello',
    // Add more English translations here
    //login page
    email:"Email",
    password:"Password",
    login:"Login",
    forgotPassword:"Forgot Password?",
    signUp:"Sign Up",
    loginPassError:"Password is required",
    loginEmailError:"Email is required",
    username:"Username",
    confirmPassword:"confirm password",
    signIn:"Sign In",
    register:"Register",
    privacy:"Privacy Policy",
    createyouraccount:"Create your account",
    notmatch:"Passwords do not match.",
    txtConfirmpass:"Please confirm your password.",
    txtEmailError:"Invalid email address.",
    passlenthError:"Password must be at least 6 characters long.",
    usernameError:"Username is required",
    ageError:"Age is required",
    educationError:"Education is required",
    policyError:"Please accept our privacy policy",
    //time strings
    day:"day",
    s:"s",
    ago:"ago",
    hr:"hr",
    min:"min",
    sec:"sec",

    //profile
    phonenumber:"Phone Number",
    proffesion:"Proffession",
    interests:"Interests",
    progress:"Progress",
    //edit profile
    firstName:"First name",
    lastName:"Last name",
    gender:"Gender",
    age:"Age",
    updateProfile:"Save",
    education:"Education",
    languages:"Languages",
    skills:"Skills",
    myGallery:"My Gallery",
    bio:"Bio",
    cv:"Cv",
    from:"From",
    uploaded:"Uploaded",
    attachCv:"Attach Cv",
    myUploads:"My Uploads",
    saveYourImages:"Save Your Images",
    selectAnImage:"Select an image",
    uploading:"Uploading",

    //settings
    logout:"Logout",
    viewProfile:"View Profile",
    hideProfile:"Hide Profile",
    termsOfService:"TERMS OF SERVICE",
    privacyPolicy:"PRIVACY POLICY",
    getPremium:"GET A PREMIUM",
    perMonth:"per Month",
    deletAccount:"DELETE ACCOUNT",
    jobTypes:"Job Types",
    jobCategories:"Job Categories",
    //jobCard
    description:"Description",
    posted:"Posted",

    //Job Details
    rolesandresponsibilities:"Roles and Responsibilities:",
    qualifcations:"Qualifications and Requirements",
    perYear:"/ Year",
    jobDesc:"Job Description",
    proceedToapplication:"Proceed to Application",

    //chat
    chatWith:"Chat with",
    typeYourMsg:"Type your message",
    startChat:"Start Chat",

    //alerts
    locationPermission:"Location Permission Required",
    enableGPS:"Please enable GPS to use this app Efficiently",
    cancel:"Cancel",
    turnOnGPS:"Turn On GPS",

    //other
    resume:"Resume",
    select:"Select",
    addYourSkill:"add your skill",
    selectCategories:"Select Categories",
    selectedCategories:"Selected Categories",
    options:"Options",
    distanceRange:"Distance Range",
    congratulations:"Congratulations!",
    itsAmatch:"It's a match!",
    noJobsAvailable:"No Jobs Available",
    ageRange:"Age Range",
    yrs:"years",
    region:"Region",
    selectEducation:"Select Education",
    maxSelection:"You have reached maximum selection! Please upload or refresh to update",
    delImage:"Delete Image",
    delImageConfirmation:"Are you sure you want to delete this image?",
    del:"Delete",
    elementaryEducation:"Elementary Education",
    secondaryEducation:"Secondary Education",
    bachelorsDegree:"Bachelor's Degree",
    mastersDegree:"Masters Degree",


  };
  