export default {
    welcomeMessage: 'שלום',
    // Add more Hebrew translations here
    //login page
    email:"אימייל",
    password:"סיסמא",
    login:"התחברות",
    forgotPassword:"שכחת סיסמא?",
    signUp:"הרשמה",
    loginPassError:"נדרשת סיסמא",
    loginEmailError:"נדרש אימייל",
    username:"שם משתמש",
    confirmPassword:"אשר סיסמא",
    signIn:"התחברות",
    register:"הרשמה",
    privacyPolicy:"מדיניות פרטיות",
    createyouraccount:"פתח משתמש חדש",
    notmatch:"הסיסמאות לא תואמות",
    txtConfirmpass:"אשר את הסיסמה שלך",
    txtEmailError:"כתובת אימייל לא חוקית.",
    passlenthError:"הסיסמה חייבת להיות באורך של לפחות 6 תווים.",
    usernameError:"נדרש שם משתמש",
    //time strings
    day:"יום",
    s:"s",
    ago:"לפני",
    hr:"שעות",
    min:"דקות",
    sec:"שניות",

    //profile
    phonenumber:"מספר טלפון",
    proffesion:"מקצוע",
    interests:"תחומי עניין",
    progress:"הושלמו",
    //edit profile
    firstName:"שם פרטי",
    lastName:"שם משפחה",
    gender:"מגדר",
    age:"גיל",
    updateProfile:"שמירה",
    education:"השכלה",
    languages:"שפות",
    skills:"מיומנויות",
    myGallery:"הגלריה שלי",
    bio:"ביבליוגרפיה",
    cv:'קו"ח',
    from:"מ",
    uploaded:"הועלה",
    attachCv:"צרף קורות חיים",
    myUploads:"ההעלאות שלי",
    saveYourImages:"שמור את התמונות שלך",
    selectAnImage:"בחר תמונה",
    uploading:"בהעלאה",

    //settings
    logout:"יציאה",
    viewProfile:"צפה בפרופיל",
    hideProfile:"הסתר פרופיל",
    termsOfService:"תנאי השירות",
    privacyPolicy:"מדיניות פרטיות",
    getPremium:"משתמש פרימיום",
    perMonth:"לחודש",
    deletAccount:"מחק חשבון",
    jobTypes:"סוגי עבודות",
    jobCategories:"קטגוריות עבודה",

    //jobCard
    description:"תיאור",
    posted:"פורסם",

    //Job Details
    rolesandresponsibilities:"תפקידים ואחריות:",
    qualifcations:"כישורים ודרישות",
    perYear:"\ שנה",
    jobDesc:"תיאור המשרה",
    proceedToapplication:"המשך ליישום",

     //chat
     chatWith:"צ'אט עם",
     typeYourMsg:"רשום את ההודעה שלך",
     startChat:"התחל צ'אט",

      //alerts
    locationPermission:"נדרשת הרשאת מיקום",
    enableGPS:"בבקשה אשר את הפעלת ה-GPS לצורך שימוש באפליקציה",
    cancel:"ביטול",
    turnOnGPS:"הפעיל GPS",


    //other
    resume:"קורות חיים",
    select:"בחר",
    addYourSkill:"הוסף את המומחיות שלך",
    selectCategories:"בחר קטגוריות",
    selectedCategories:"קטגוריות נבחרות",
    options:"אפשרויות",
    distanceRange:"טווח מרחק",
    congratulations:"מזל טוב !",
    itsAmatch:"יש התאמה !",
    noJobsAvailable:"אין משרות פנויות",
    ageRange:"טווח גילאים",
    yrs:"שנים",
    region:"איזור",
    selectEducation:"בחר השכלה מתאימה",
    maxSelection:"הגעת למבחר המקסימלי ! אנא העלה או רענן כדי לעדכן",
    delImage:"מחק תמונה",
    delImageConfirmation:"האם אתה בטוח שברצונך למחוק את התמונה הזו?",
    del:"מחק תמונה",
    elementaryEducation:"ללא תעודת בגרות",
    secondaryEducation:"תעודת בגרות מלאה",
    bachelorsDegree:"תואר ראשון",
    mastersDegree:"תואר שני",
  };
  